### ISSUE TITLE
It's impossible to install

### ISSUE THREAD

**Issue by Magneticdud** [i7MEDIA/mojoPortal-WebStore#2]
> it was moved to its own project so people who need it can download it

this... needs to be compiled? I have no idea how to do it without documentation. I need to install a monster like visual studio?

now i broke my website upgrade because I deleted the old files and I get error 500...

Luckily I backupped the older version database...

**Comment by JosephMDavis** [comment]
Hi,

I'm sorry, this came through while I was on vacation and I didn't notice it until now. You can download the compiled webstore from [here](https://github.com/i7MEDIA/mojoportal/releases/tag/v2.6.0.0). It's listed at the bottom of the release files for mojoPortal 2.6.

Thanks,
Joe
